### ISSUE TITLE
Questions about generating multiple images at once

### ISSUE THREAD

**Issue by cch-meiple** [omriav/blended-diffusion#20]
Hi, thank you for your interesting work!

In a classification or detection task, batch size can be used to infer multiple images at once. However, in blended diffusion, the batch size is an argument for how many images to generate for one image. Is there an argument for generating multiple images at once, and if not, how should it be changed? 

Thanks!

**Comment by omriav** [comment]
Hi,
Thank you very much for your interest.
You are correct, the problem is that in Blended Diffusion there is a need to generate multiple images for the same prompt, then rank them and get the best ones.
By the way, you should check the newer work of [Blended Latent Diffusion](https://github.com/omriav/blended-latent-diffusion) which is significantly faster and requires fewer images to generate.
